// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS3sTydyPHYNrVT3-_9rUPwDe0jKsC0Sg',
    appId: '1:808820460405:web:8eedca503d3d07a8ba213c',
    messagingSenderId: '808820460405',
    projectId: 'to-do-app-6d3b7',
    authDomain: 'to-do-app-6d3b7.firebaseapp.com',
    storageBucket: 'to-do-app-6d3b7.appspot.com',
    measurementId: 'G-DCP2HN1DSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkTTIyeScpGfBNYoNyC9hwGDJuttz29GI',
    appId: '1:808820460405:android:29da21218e98afd3ba213c',
    messagingSenderId: '808820460405',
    projectId: 'to-do-app-6d3b7',
    storageBucket: 'to-do-app-6d3b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjET8zreCfze64xAzur3uijjU227Y-X3s',
    appId: '1:808820460405:ios:1ef6d524de60ffacba213c',
    messagingSenderId: '808820460405',
    projectId: 'to-do-app-6d3b7',
    storageBucket: 'to-do-app-6d3b7.appspot.com',
    iosBundleId: 'com.example.clientServer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjET8zreCfze64xAzur3uijjU227Y-X3s',
    appId: '1:808820460405:ios:6906668c2ad065abba213c',
    messagingSenderId: '808820460405',
    projectId: 'to-do-app-6d3b7',
    storageBucket: 'to-do-app-6d3b7.appspot.com',
    iosBundleId: 'com.example.clientServer.RunnerTests',
  );
}
